-- https://raw.githubusercontent.com/sakaiproject/sakai/master/samigo/docs/auto_submit/auto_submit_mysql.sql

INSERT INTO SAM_ASSESSMETADATA_T (ASSESSMENTMETADATAID, ASSESSMENTID, LABEL, ENTRY) VALUES (NULL, 1, 'automaticSubmission_isInstructorEditable', 'true');

-- Run these SQL commands to update the templates
CREATE TEMPORARY TABLE UPDATE_SAM_AUTO_IDS AS (SELECT ID FROM SAM_ASSESSMENTBASE_T WHERE TYPEID='142' AND ISTEMPLATE=1);
-- You may need to clean this up if you've run it multiple times
-- DELETE FROM SAM_ASSESSMETADATA_T WHERE ASSESSMENTID IN (SELECT ID FROM UPDATE_SAM_AUTO_IDS) AND LABEL='automaticSubmission_isInstructorEditable';
INSERT INTO SAM_ASSESSMETADATA_T (ASSESSMENTMETADATAID, ASSESSMENTID, LABEL, ENTRY) SELECT NULL, ID, 'automaticSubmission_isInstructorEditable', 'true' FROM UPDATE_SAM_AUTO_IDS;
DROP TABLE UPDATE_SAM_AUTO_IDS;


-- Run these SQL commands to back fill to your existing assessments
CREATE TEMPORARY TABLE UPDATE_SAM_AUTO_IDS AS (SELECT ID FROM SAM_ASSESSMENTBASE_T WHERE ID NOT IN (SELECT ASSESSMENTID FROM SAM_ASSESSMETADATA_T WHERE label = 'automaticSubmission_isInstructorEditable'));
INSERT INTO SAM_ASSESSMETADATA_T (ASSESSMENTMETADATAID, ASSESSMENTID, LABEL, ENTRY) SELECT NULL, ID, 'automaticSubmission_isInstructorEditable', 'true' FROM UPDATE_SAM_AUTO_IDS;
DROP TABLE UPDATE_SAM_AUTO_IDS;

-- Add an automatic link to TsugiCloud Test
INSERT INTO `lti_tools` (`SITE_ID`, `title`, `allowtitle`, `fa_icon`, `pagetitle`, `allowpagetitle`, `description`, `status`, `visible`, `launch`, `allowlaunch`, `consumerkey`, `allowconsumerkey`, `secret`, `allowsecret`, `frameheight`, `toolorder`, `allowframeheight`, `siteinfoconfig`, `sendname`, `sendemailaddr`, `allowoutcomes`, `allowroster`, `allowsettings`, `pl_launch`, `pl_linkselection`, `pl_contenteditor`, `pl_importitem`, `pl_fileitem`, `pl_assessmentselection`, `newpage`, `debug`, `custom`, `allowcustom`, `lti13`, `lti13_settings`, `xmlimport`, `splash`, `created_at`, `updated_at`, `sha256`) VALUES
(NULL, 'TsugiCloud App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL, NOW(), NOW(), 0);

-- Add automatic link to WarpWire nightly
INSERT INTO `lti_tools` (`SITE_ID`, `title`, `allowtitle`, `fa_icon`, `pagetitle`, `allowpagetitle`, `description`, `status`, `visible`, `launch`, `allowlaunch`, `consumerkey`, `allowconsumerkey`, `secret`, `allowsecret`, `frameheight`, `toolorder`, `allowframeheight`, `siteinfoconfig`, `sendname`, `sendemailaddr`, `allowoutcomes`, `allowroster`, `allowsettings`, `pl_launch`, `pl_linkselection`, `pl_contenteditor`, `pl_importitem`, `pl_fileitem`, `pl_assessmentselection`, `newpage`, `debug`, `custom`, `allowcustom`, `lti13`, `lti13_settings`, `xmlimport`, `splash`, `created_at`, `updated_at`, `sha256`) VALUES
(NULL, 'WarpWire Test Server', 1, NULL, 'WarpWire Test Server', 0, NULL, 0, 0, 'https://sakainightly.warpwire.net/api/ltix/?mode=plugin', 1, 'lti:sakainightly:01', 0, 'gsAM:wUeZRn2-kJERm-OkqrKB-nJxdke-webMOj-pj8vL2', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL, NOW(), NOW(), 0);
 

INSERT INTO `lti_tools` (`id`, `SITE_ID`, `title`, `allowtitle`, `fa_icon`, `allowfa_icon`, `pagetitle`, `allowpagetitle`, `description`, `status`, `visible`, `deployment_id`, `launch`, `allowlaunch`, `consumerkey`, `allowconsumerkey`, `secret`, `allowsecret`, `frameheight`, `toolorder`, `allowframeheight`, `siteinfoconfig`, `sendname`, `sendemailaddr`, `allowoutcomes`, `allowlineitems`, `allowroster`, `allowsettings`, `pl_launch`, `pl_linkselection`, `pl_contenteditor`, `pl_importitem`, `pl_fileitem`, `pl_assessmentselection`, `newpage`, `debug`, `custom`, `rolemap`, `allowcustom`, `splash`, `lti13`, `lti13_client_id`, `lti13_tool_public`, `lti13_tool_keyset`, `lti13_tool_kid`, `lti13_tool_private`, `lti13_platform_public`, `lti13_platform_private`, `lti13_oidc_endpoint`, `lti13_oidc_redirect`, `lti13_settings`, `sha256`, `lti11_launch_type`, `xmlimport`, `created_at`, `updated_at`) VALUES
(74, NULL, 'CourseNetworking CNPost', 0, NULL, 0, 'CNPost', 0, 'This is an LTI service provided by CourseNetworking (thecn.com).  It is both a threaded discussion system (CNPost) that is part of a global student portfolio system (TheCN).  This is a test key, please contact CourseNetworking for your own key.  For more details, see https://support.thecn.com/hc/en-us/articles/235243908', 0, 0, NULL, 'https://www.thecn.com/program/lti/course', 0, '5e33510fc417ed6dfe59cb37', 0, '9a4c3f260d173e3fa434d5ae', 0, NULL, NULL, 0, 0, 1, 1, 1, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, '2020-02-25 09:22:06', '2020-02-25 09:22:06');

-- Add a lot of tools and links so that we can test paging easily after changes like SAK-39962
-- These are all inserted into site mercury so only the admin sees them
-- This is kind of repetitive so best to add new queries above this block

INSERT INTO `lti_tools` (`SITE_ID`, `title`, `allowtitle`, `fa_icon`, `pagetitle`, `allowpagetitle`, `description`, `status`, `visible`, `launch`, `allowlaunch`, `consumerkey`, `allowconsumerkey`, `secret`, `allowsecret`, `frameheight`, `toolorder`, `allowframeheight`, `siteinfoconfig`, `sendname`, `sendemailaddr`, `allowoutcomes`, `allowroster`, `pl_launch`, `pl_linkselection`, `pl_contenteditor`, `pl_importitem`, `pl_fileitem`, `pl_assessmentselection`, `newpage`, `debug`, `custom`, `lti13`, `lti13_settings`, `xmlimport`, `splash`, `created_at`, `updated_at`) VALUES
('mercury', 'TsugiClone 10 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 11 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 12 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 13 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 14 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 15 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 16 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 17 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 18 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 19 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 20 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 21 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 22 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 23 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 24 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 25 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 26 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 27 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 28 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 29 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 30 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 31 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 32 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 33 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 34 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 35 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 36 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 37 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 38 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 39 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 40 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 41 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 42 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 43 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 44 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 45 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 46 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 47 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 48 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 49 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 50 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 51 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 52 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 53 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 54 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 55 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 56 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 57 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 58 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 59 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 60 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 61 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 62 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 63 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 64 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 65 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 66 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 67 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 68 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 69 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 70 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 71 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 72 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 73 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 74 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 75 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 76 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 77 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 78 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
('mercury', 'TsugiClone 79 App Store', 1, NULL, 'TsugiCloud App Store', 0, NULL, 0, 0, 'https://test.tsugicloud.org/tsugi/lti/store/', 1, '12345', 0, 'secret', 0, NULL, NULL, 0, 0, 1, 1, 1, 1, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, 0, NULL, NULL, NULL, NOW(), NOW())
;

INSERT INTO `lti_content` (`tool_id`, `SITE_ID`, `title`, `description`, `pagetitle`, `fa_icon`, `frameheight`, `toolorder`, `newpage`, `protect`, `debug`, `custom`, `launch`, `consumerkey`, `secret`, `xmlimport`, `settings`, `settings_ext`, `contentitem`, `placement`, `placementsecret`, `oldplacementsecret`, `lti13`, `lti13_settings`, `created_at`, `updated_at`) VALUES
(1, 'mercury', 'Content 10', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 11', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 12', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 13', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 14', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 15', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 16', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 17', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 18', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 19', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 20', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 21', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 22', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 23', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 24', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 25', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 26', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 27', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 28', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 29', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 30', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 31', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 32', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 33', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 34', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 35', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 36', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 37', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 38', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 39', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 40', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 41', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 42', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 43', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 44', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 45', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 46', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 47', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 48', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 49', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 50', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 51', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 52', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 53', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 54', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 55', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 56', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 57', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 58', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 59', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 60', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 61', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 62', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 63', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 64', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 65', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 66', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 67', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 68', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 69', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 70', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 71', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 72', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 73', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 74', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 75', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 76', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 77', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 78', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
(1, 'mercury', 'Content 79', 'This tool fills space.', 'PY4E', NULL, NULL, NULL, 0, 0, 0, '', 'http://localhost:8888/py4e/mod/lmstest/', NULL, NULL, NULL, '{"description":"This tool fills space.\r\n"}', NULL, '', NULL, '98c6490f-6a5c-41aa-ac13-d16f4d6af5a5', NULL, 0, NULL, NOW(), NOW())
;


